### ISSUE TITLE
native:printlayouttopdf and print as raster option

### ISSUE THREAD

**Issue by Michael-cd30** [paleolimbot/qgisprocess#100]
Hello,

The "native:printlayouttopdf" command seems to ignore the state of the "print as raster" checkbox.
It is also not possible to ask for a rastered map using the input parameters.

Regards,

**Comment by florisvdh** [comment]
In below QGIS dialog window, I see a checkbox 'always export as vectors', which should be reflected by the `FORCE_VECTOR` argument, see screenshot.

![afbeelding](https://user-images.githubusercontent.com/19164640/172354962-85a65f4c-dfe2-4607-92c3-dbab1bdb1abf.png)

This is in QGIS 3.24.3, where it is possible (see the 'Advanced' dropdown) to export code e.g. a JSON string, and use it as input for `qgisprocess`:

```json
{
  "area_units": "m2",
  "distance_units": "meters",
  "ellipsoid": "EPSG:7022",
  "inputs": {
    "DISABLE_TILED": false,
    "DPI": null,
    "FORCE_VECTOR": false,
    "GEOREFERENCE": true,
    "INCLUDE_METADATA": true,
    "LAYERS": null,
    "LAYOUT": "testlayout",
    "OUTPUT": "TEMPORARY_OUTPUT",
    "SEPARATE_LAYERS": false,
    "SIMPLIFY": true,
    "TEXT_FORMAT": 0
  }
}
```

**Comment by Michael-cd30** [comment]
Hi @florisvdh ,

According to the documentation, the default value for force_vector is false, see:
https://github.com/qgis/QGIS-Documentation/blob/268c383d2038ba177fc1be39d8f81b438c0c5397/docs/user_manual/processing_algs/qgis/cartography.rst#export-print-layout-as-pdf

I've tried to explicitly pass this argument to "false" on the command line.

The verbose output shows that it's correctly received :

----------------
Inputs
----------------

**FORCE_VECTOR:	FALSE**
LAYOUT:	A3
OUTPUT:	...


Successfully exported layout to ....
0...10...20...30...40...50...60...70...80...90...100 - done.

----------------
Results
----------------

OUTPUT:	...

But the resulting map is still not rastered.

Regards,

**Comment by florisvdh** [comment]
If you execute it from the QGIS processing dialog window, do you get the same?

**Comment by Michael-cd30** [comment]
No, when I export PDF from QGis with
"Print as raster" : checked
"Always export as vectors" : unchecked

The map is rastered.
The PDF size is 2,82Mo whereas its size is 5,36Mo with qgis_process.

![image](https://user-images.githubusercontent.com/64089998/172566306-5968e35b-7ded-49f6-b693-91d8a3d66942.png)
![image](https://user-images.githubusercontent.com/64089998/172566567-02479488-0715-451a-bc40-10c793226897.png)

**Comment by florisvdh** [comment]
Do you use the `qgis_process` shell command directly, or within R, through `qgisprocess::qgis_run_algorithm()`?

Just to make sure: this repository is the R package `qgisprocess` (no underscore), which calls the `qgis_process` shell command. If the problem is with the `qgis_process` shell command, the R package won't solve it, so in that case you should make an issue at https://github.com/qgis/QGIS/issues/new/choose instead and be explicit about the QGIS version you are using. Problems may be solved in latest QGIS release (in 3.24.3 I see no 'Print as raster' checkbox).

**Comment by Michael-cd30** [comment]
I'm using a Windows version.

I run this file "qgis_process-qgis-ltr.bat" which sets environment variables and then starts "%OSGEO4W_ROOT%\apps\qgis-ltr\bin\qgis_process.exe"

So I close this issue and will open another one directly on QGis repo.

Sorry for the mistake and thanks for your help.

NB : I use the LTR 3.22.7

**Comment by florisvdh** [comment]
> So I close this issue and will open another one directly on QGis repo.

Thanks for opening https://github.com/qgis/QGIS/issues/48921 (referring here as a reference).
