### ISSUE TITLE
Native:buffer writing the dynamic distance

### ISSUE THREAD

**Issue by AntoineCastet** [paleolimbot/qgisprocess#101]
Hello,

Thank you a lot for this amazing package which is really useful.

I have a question relative to the "native:buffer" algorithm. 

I would like to create a dynamic distance buffer according to the value of the numeric variable "Size". The file's name is "File". 

I try to write (among others tries): 
           File= st_read("Path/File.shp" )
           qgis_run_algorithm(
                    "native:buffer", 
                    INPUT = File,
                    Distance = File$Size
                     )

But it seems that is not the appropriate way to create a dynamic distance buffer.  The documentation precises that the acceptable values are "numeric". Does that mean it is not possible to create dynamic distance buffer through a variable? If it is possible, what is the correct way to do it?

Thanks by advance for your help.

Sincerely

**Comment by idshklein** [comment]
when I run the buffer tool in qgis, and use a variable to to determine the distance, this dictionary appears in the log:
![image](https://user-images.githubusercontent.com/12258810/172583079-1345341e-3b59-4f85-9423-a3edfbb41033.png)
I would assume that playing with this kind of python qgis functions could help. 
I assume the question doesn't relate to the buffer tool, as sf::st_buffer can achieve all of the above

**Comment by florisvdh** [comment]
@idshklein can a `qgis_process` command be extracted from the processing dialog (see 'Advanced' dropdown), that can be run from the shell, hence can be transformed into the `qgisprocess::qgis_run_algorithm()` syntax? An alternative is the use of the JSON string (same dropdown), which `qgisprocess::qgis_run_algorithm()` also supports.

**Comment by florisvdh** [comment]
@idshklein just now I notice that your screenshot mentions QGIS version 3.16. The extraction of a `qgis_process` command string or the JSON representation of the parameters, from the 'Advanced' dropdown is a feature that appeared for the first time in QGIS 3.24 though.

I've checked for this case whether it would at all be possible. At least it can be concluded that no functional `DISTANCE` parameter is exported from the dropdown when selecting an attribute that defines the buffer distance: the exported `qgis_process` command shows a value-less `--DISTANCE=` and the JSON string has `"DISTANCE": null`. It's unclear to me whether it is at all possible to include the expression and make it work (Python example: `'DISTANCE':QgsProperty.fromExpression('"OBJ"')`), despite the dropdown not exporting this kind of parameter setting.

Any thoughts on this @nyalldawson? Is this worth creating an issue at QGIS?
