### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by jrojasquiroz** [paleolimbot/qgisprocess#55]
Hi, sorry if this question is kind of basic but I'm new in R and a non-english speaker.
After installing the package, I run `library(qgisprocess)` and this message appears:
```
The 'qgis_process' command-line utility was not found.
Run 'qgis_configure()' for details.
```

So, i run it and then this appears:
```
getOption('qgisprocess.path') was not found.
Sys.getenv('R_QGISPROCESS_PATH') was not found.
Trying 'qgis_process' on PATH
Error in processx::run("cmd.exe", c("/c", "call", path, args), ...): System command 'cmd.exe' failed, exit status: 1, stderr:
E> "qgis_process" no se reconoce como un comando interno o externo,
E> programa o archivo por lotes ejecutable.

No QGIS installation containing 'qgis_process' found!
```
I have installed QGIS 3.16.7 and as much as I understand `qgis_process` command-line utility is available in versions >= 3.14.16, so I do not know what more else I have to install or configure. 
Thanks in advance.

**Comment by JanCaha** [comment]
You probably have QGIS in non-standard location. `qgisprocess` only goes so far to test the most common locations. So if you installed QGIS elsewhere your best bet is to set `options(qgisprocess.path = "path/to/qgis_process")` before loading the library.
