### ISSUE TITLE
Arguments for some functions cannot be obtained with JSON output

### ISSUE THREAD

**Issue by JanCaha** [paleolimbot/qgisprocess#85]
This code fails:
```
library(qgisprocess)
options(qgisprocess.use_json_output = TRUE)
qgis_configure()
# just to take a look that it is TRUE
qgis_use_json_output()
qgis_arguments("qgis:executesql")
```

The problem is in these lines: 
https://github.com/paleolimbot/qgisprocess/blob/4a795400af9e4a8b916ee7cda748f5f7fc043af7/R/qgis-help.R#L37
https://github.com/paleolimbot/qgisprocess/blob/4a795400af9e4a8b916ee7cda748f5f7fc043af7/R/qgis-help.R#L40

As these requested values are lists of length 0. I understand the issue but cannot quite figure out simple way to fix it.

There are 37 algorithms with the same issue. I came across it yesterday when automatic build of (**qgis**)[https://github.com/JanCaha/r_package_qgis] failed. The solution is simple, manually set the `options(qgisprocess.use_json_output = FALSE)`, but the problem needs to be adressed.

**Comment by florisvdh** [comment]
@JanCaha can you have a look whether PR #87 is a solution for this problem, and test its potential further implications for `qgis:executesql`?

**Comment by JanCaha** [comment]
Solves this and couple of other algorithms that caused problems! Thanks a lot :+1:
