### ISSUE TITLE
Error : lexical error: invalid char in json text.

### ISSUE THREAD

**Issue by Dieunicos** [paleolimbot/qgisprocess#90]
R version 4.0.2 (2020-06-22) 

> require(qgisprocess)
Le chargement a nécessité le package : qgisprocess
Using 'qgis_process' at 'C://OSGeo4W64/bin/qgis_process-qgis.bat'.
QGIS version: 3.16.3-Hannover
Configuration loaded from 'C:\Users\latte.n\AppData\Local/R-qgisprocess/R-qgisprocess/Cache/cache-0.0.0.9000.rds'
Run `qgis_configure()` for details.
Using JSON for output serialization
> 
> input <- sf::read_sf(system.file("shape/nc.shp", package = "sf"))
> 
> result <- qgis_run_algorithm(
+    "native:buffer",
+    INPUT = input,
+    DISTANCE = 1,
+    DISSOLVE = TRUE,
+    .quiet = TRUE
+  )
Error : lexical error: invalid char in json text.
                                       C:\Users\latte.n\Documents  {  
                     (right here) ------^

Erreur : lexical error: invalid char in json text.
                                       C:\Users\latte.n\Documents  {  
                     (right here) ------^

**Comment by jannes-m** [comment]
Just guessing here, but try to set the OUTPUT argument yourself while using a path which does **not** contain a dot like `latte.n`.
