### ISSUE TITLE
Returning terra's objects

### ISSUE THREAD

**Issue by Nowosad** [paleolimbot/qgisprocess#92]
Currently, **qgisprocess** allows to read vector outputs of **qgisprocess** with `st_as_sf()` and raster outputs with `st_as_stars()` (https://github.com/paleolimbot/qgisprocess/blob/4a795400af9e4a8b916ee7cda748f5f7fc043af7/R/zzz.R#L7). However, would it be possible to add an option for reading **terra's** objects? Currently, reading **terra's** objects require using the `unclass()` function, which is rather unintuitive for new users and beginners. I understand that **terra** is based on S4 (not S3 like **sf**), but maybe there is another way to implement a more straightforward read of **qgisprocess**'s rasters to **terra**?

``` r
library(qgisprocess)
#> Using 'qgis_process' at 'qgis_process'.
#> QGIS version: 3.20.3-Odense
#> Configuration loaded from '~/.cache/R-qgisprocess/cache-0.0.0.9000.rds'
#> Run `qgis_configure()` for details.
#> Using JSON for output serialization
library(terra)
#> terra 1.5.23
dem = rast(system.file("raster/dem.tif", package = "spDataLarge"))
dem_wetness = qgis_run_algorithm("saga:sagawetnessindex", 
                                 DEM = dem)
#> ...

dem_wetness_1 = rast(dem_wetness)
#> Error in methods::as(x, "SpatRaster"): no method or default for coercing "qgis_result" to "SpatRaster"

dem_wetness_2 = rast(dem_wetness$AREA)
#> Error in methods::as(x, "SpatRaster"): no method or default for coercing "qgis_outputRaster" to "SpatRaster"

dem_wetness_3 = rast(unclass(dem_wetness$AREA))
```

<sup>Created on 2022-02-24 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by florisvdh** [comment]
There is the **qgisprocess** function `qgis_as_terra()` - does that work? Should work for `qgis_outputRaster` and `qgis_result` classes (in the latter case, it tries to guess the most relevant element, preferably named like 'output', otherwise takes the first element).

**Comment by Nowosad** [comment]
Thank you a lot @florisvdh! I totally forgot about this function.
