### ISSUE TITLE
'Zonal statistics' overwrites input vector

### ISSUE THREAD

**Issue by arnopauwels** [paleolimbot/qgisprocess#98]
Hi,

I've noticed something weird when I run the `native:zonalstatistics` algorithm. 

I'm using the tool to calculate some basic stats (mean, min, max) for zones defined in a polygon vector layer. What I get is:

```
zonal_stats = qgis_run_algorithm(
                     "native:zonalstatistics",
                     INPUT_RASTER = 'raster.tif', 
                     RASTER_BAND = 1,
                     INPUT_VECTOR = 'vector.shp',
                     COLUMN_PREFIX = 'Stat_',
                     STATISTICS = c(2,5,6)
                     )
#> <string>:1: DeprecationWarning: setapi() is deprecated
#> Warning 1: Value 12259440.0412000008 of field Shape_Area of feature 121 not successfully written. Possibly due to too larger number with respect to field width
#> Warning 1: Value 10976697.9250000007 of field Shape_Area of feature 411 not successfully written. Possibly due to too larger number with respect to field width
...
```
with dozens of those warnings.

If I try to read the file of which the path is specified in the `zonal_stats` result, I get an error telling me it does not exist:

```
sf::read_sf(zonal_stats[[1]])
#> Error: Cannot open "sh_statbel_statistical_sectors_20210101_3f635449_9e11_4d35_a3dd_b00c2b421698"; The file doesn't seem to exist.
```
So apparently, running the algorithm does not create an output file. But when I check the original shapefile `vector.shp`, three columns are added, each containing one of the specified statistics. Running `qgis_show_help("native:zonalstatistics")` also contains the following for outputs:

```
----------------
Outputs
----------------

INPUT_VECTOR: <outputVector>
	Zonal statistics
```
which seems to suggest the output gets written to the input vector, instead of creating a temporary file. 

Is this supposed to happen? Is it possible to save the result as a temp file instead of overwriting?

Thanks for clarifying.

PS: I ran Zonal statistics in QGIS  itself, same version (3.22.5) with the exact same files, and none of these issues occurred. The GUI does provide the option to save the result to a new file. I'm Using Win10.

**Comment by arnopauwels** [comment]
Thank you for responding.

I am positive my input vector file was overwritten. I wrote a small script `zonal_stats_test.R` that performs the same operation on two generated features (I added plots to make clear what they look like). The same error is returned as compared to my example above:

```
#install.packages("qgisprocess")
#install.packages("sf")
#install.packages("terra")

library(qgisprocess) 
library(sf)
library(terra)

# Create raster
raster <- terra::rast(
  nrows = 10, ncols = 10, resolution = 1, 
  xmin = 0, xmax = 10, ymin = 0, ymax = 10,
  vals = 1:100)
plot(raster)
terra::writeRaster(raster, 'raster.tif')

# Create vector
box <- matrix(c(1,1,9,1,9,9,1,9,1,1),ncol=2, byrow=TRUE)
geo <- sf::st_sfc(st_polygon(list(box)))
polygon <- sf::st_sf(ID=1, geo)
plot(polygon, add=TRUE) 
sf::write_sf(obj=polygon, dsn='vector.shp')

# Calculate zonal stats
zonal_stats <- qgis_run_algorithm(
  "native:zonalstatistics",
  INPUT_RASTER = 'raster.tif', 
  RASTER_BAND = 1,
  INPUT_VECTOR = 'vector.shp',
  COLUMN_PREFIX = 'Stat_',
  STATISTICS = c(2,5,6)
  )

# Read output file
list.files(read_sf(zonal_stats[[1]]))

#> Error: Cannot open "vector_875e0936_0ccd_4bb6_bd51_00fd14b2aba4"; The file doesn't seem to exist.

```

This also results in the 'non-existing file' error:

```
output_sf <- sf::read_sf(qgis_output(zonal_stats, "INPUT_VECTOR"))
#> Error: Cannot open "vector_875e0936_0ccd_4bb6_bd51_00fd14b2aba4"; The file doesn't seem to exist.
```

The temp folder is indeed empty. 

When I check the input vector `vector.shp`, the columns with the stats are added, so like in the case above the input file gets overwritten (I added a screenshot). 

Hope this was helpful, thanks for looking into it.


![Generated_raster_and_vector](https://user-images.githubusercontent.com/105283821/167663859-03291c7e-2da3-4859-9318-c07fce47e9c7.png)

![Input_vector_table](https://user-images.githubusercontent.com/105283821/167663854-70d87602-c8aa-4caa-a4b4-9ada70731714.png)

**Comment by nicogodet** [comment]
`native:zonalstatistics` alters input layer.
If you want a new layer and leave input untouched, use `native:zonalstatisticsfb`.

ref: https://github.com/qgis/QGIS/pull/38650

**Comment by florisvdh** [comment]
Thank you for the help @nicogodet!

@arnopauwels I guess this solves your issue?
